apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: softy-erp
  namespace: softy-erp
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
        - api.erp.soft-y.org
      secretName: erp-tls
  rules:
    - host: api.erp.soft-y.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: softy-erp
                port:
                  number: 80
